name = "thyme"
version = "0.1.0"
description = "Type-safe staged programming supporting dependent types and reasoning about metaprograms."
license = "Apache-2.0"
defaultTargets = ["Thyme"]
testDriver = "ThymeTests"

[leanOptions]
backward.do.legacy = true

[[lean_lib]]
name = "Thyme"
precompileModules = true

[[lean_lib]]
name = "ThymeTests"
