name = "thyme"
version = "0.1.0"
description = "Typed metaprogramming based on staging, with support for dependent types and reasoning about metaprograms."
license = "Apache-2.0"
defaultTargets = ["Thyme"]
testDriver = "ThymeTests"

[leanOptions]
backward.do.legacy = true

[[lean_lib]]
name = "Thyme"
precompileModules = true

[[lean_lib]]
name = "ThymeTests"
leanOptions.weak.thyme.checkCoherence = true
